Repository emuflight/EmuFlight, pull requests merged in 2020-03, with the labels that each got.

#98 master of none (and Main)
  .github/issue_template.md
  .github/pull_request_template.md
  README.md
Labels: documentation

#103 fix filterGetNotchQ
  src/main/common/filter.c
Labels: bug

#107 remove lagging average filter from code
  src/main/common/filter.c
  src/main/common/filter.h
Labels: enhancement

#105 create funding meta
  .github/FUNDING.yml
Labels: documentation

#102 Change GCC optimization of kalman.c and move critical code to ITCM_RAM
  make/source.mk
  src/main/common/kalman.c
Labels: enhancement

#106 moved codacy to orga scope so new badge
  .github/stale.yml
  README.md
Labels: enhancement

#104 Kalman cleanup
  src/main/common/kalman.c
  src/main/common/kalman.h
Labels: enhancement

#109 Remove jitter in the accelerometer
  src/main/flight/imu.c
Labels: enhancement

#101 sorta kinda semantic versioned hex filenames
  Makefile
  src/main/build/version.c
  src/main/build/version.h
Labels: enhancement

#100 update toolchain to 2019-q4-release
  make/tools.mk
Labels: enhancement

#108 Dzikuvx pid sanity
  src/main/flight/pid.c
Labels: enhancement

#111 build faster, better, wider on travis
  .travis.yml
  Makefile
  make/targets.mk
  make/tools.mk
Labels: enhancement

#113 remove cinematic setpoint
  src/main/cms/cms_menu_imu.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/settings.c
Labels: bug

#114 Gyro.c put fabsf where needed
  src/main/sensors/gyro.c
Labels: bug

#116 Remove GA Filter
  src/main/cms/cms_menu_imu.c
  src/main/interface/msp.c
  src/main/interface/settings.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/gyro_filter_impl.h
Labels: enhancement

#120 make turtle mode power output configurable
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/flight/pid.c
  src/main/interface/settings.c
Labels: feature

#121 increase max sharpness
  src/main/cms/cms_menu_imu.c
  src/main/interface/settings.c
  src/main/sensors/gyro.c
Labels: enhancement

#110 First cut of Matrix Filter
  src/main/interface/settings.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/gyro_filter_impl.h
  src/main/sensors/gyroanalyse.c
  src/main/sensors/gyroanalyse.h
Labels: enhancement

#123 Drop gyroanalyse quality factor
  src/main/interface/settings.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/gyroanalyse.c
  src/main/sensors/gyroanalyse.h
Labels: enhancement

#124 Enable matrix filter by default on non-IMUF boards
  src/main/config/feature.c
  src/main/config/feature.h
Labels: enhancement

#127 add workflow for github actions to build
  .github/workflows/build.yml
Labels: enhancement

#128 remove unused code
  src/main/flight/pid.c
Labels: enhancement

#119 add "deployment" to github release page
  .travis.sh
  .travis.yml
  Makefile
  bintray-template.j2
  build_docs.sh
  make/tools.mk
  src/main/build/version.h
Labels: enhancement

#136 USE_PEGASUS_UI
  src/main/target/common_fc_pre.h
Labels: enhancement

#135 Kaio created HGLRCF411 target
  src/main/target/HGLRCF411/target.c
  src/main/target/HGLRCF411/target.h
  src/main/target/HGLRCF411/target.mk
Labels: enhancement
