Repository emuflight/EmuFlight, pull requests merged in 2020-07, with the labels that each got.

#303 ZeezF7: fix double uart1
  src/main/target/ZEEZF7/target.h
Labels: recommend merge

#304 lots of warning fixes :)
  lib/main/STM32_USB_Device_Library/Class/msc/inc/usbd_msc_core.h
  lib/main/STM32_USB_Device_Library/Class/msc/src/usbd_msc_core.c
  lib/main/STM32_USB_OTG_Driver/src/usb_core.c
  src/main/build/atomic.h
  src/main/fc/fc_rc.c
  src/main/msc/usbd_msc_desc.c
  src/main/vcpf4/usbd_desc.c
Labels: recommend merge

#236 update the matrix filter to be like bf4.2
  src/main/cms/cms_menu_imu.c
  src/main/fc/fc_core.c
  src/main/fc/fc_core.h
  src/main/interface/settings.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/gyroanalyse.c
  src/main/sensors/gyroanalyse.h
Labels: recommend merge

#313 HGLRCF411 enable flash
  src/main/target/HGLRCF411/target.h
Labels: in-testing

#309 dterm bugfix for angle-mode
  src/main/flight/pid.c
Labels: ready for merge

#311 4 parallel builds
  .github/workflows/build.yml
  .travis.sh
  .travis.yml
  Makefile
  make/targets.mk
Labels: ready for merge

#312 SPI_CLOCK_INITIALIZATION spellcheck
  src/main/drivers/accgyro/accgyro_spi_icm20689.c
  src/main/drivers/accgyro/accgyro_spi_mpu6000.c
  src/main/drivers/accgyro/accgyro_spi_mpu9250.c
  src/main/drivers/bus_spi.h
Labels: ready for merge

#320 iDecayV2
  src/main/cms/cms_menu_imu.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/settings.c
Labels: ready for merge

#314 D boost
  src/main/cms/cms_menu_imu.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/settings.c
Labels: feature, ready for merge

#325 fix i_decay_cutoff = pidProfile->i_decay_cutoff;
  src/main/cms/cms_menu_imu.c
Labels: ready for merge

#322 add FOXEERF722V2
  src/main/target/FOXEERF722DUAL/FOXEERF722V2.mk
  src/main/target/FOXEERF722DUAL/target.h
  src/main/target/FOXEERF722DUAL/target.mk
Labels: ready for merge, target/new
