Repository emuflight/EmuFlight, pull requests merged in 2020-05, with the labels that each got.

#207 Update version.h for the release of 0.3.0
  src/main/build/version.h
Labels: on-hold

#212 make the pid calculation nondynamic
  src/main/flight/pid.c
  src/main/target/HELIOSPRING/target.h
  src/main/target/MODE2FLUX/target.h
  src/main/target/STRIXF10/target.h
Labels: enhancement

#213 20200507 kalman covar without cross influence
  src/main/common/kalman.c
  src/main/common/kalman.h
  src/main/sensors/gyro_filter_impl.h
Labels: enhancement

#257 Fix altitude display PR#256 into master
  src/main/io/osd.c
Labels: 030-maint

#253 adding MATEKF411SE
  src/main/target/MATEKF411SE/config.c
  src/main/target/MATEKF411SE/target.c
  src/main/target/MATEKF411SE/target.h
  src/main/target/MATEKF411SE/target.mk
Labels: new target

#241 fix rx bind pin not work
  src/main/target/NBDHMBF41S/target.h
Labels: 030-maint

#243 fixing some minor stuff
  src/main/target/IFF4_TWIN_G/IFF4_TWIN_G_M.mk
  src/main/target/IFF4_TWIN_G/target.h
  src/main/target/IFF4_TWIN_G/target.mk
  src/main/target/IFF7_TWIN_G/target.h
Labels: 030-maint

#262 add HGLRCF722
  src/main/target/HGLRCF722/config.c
  src/main/target/HGLRCF722/target.c
  src/main/target/HGLRCF722/target.h
  src/main/target/HGLRCF722/target.mk
Labels: new target

#247 Talon f7fusion update and iFlight updates
  src/main/target/BETAFLIGHTF4/IFF4_MINI.mk
  src/main/target/IFF411_PRO/target.h
  src/main/target/IFF4_AIO/target.h
  src/main/target/IFF4_TWIN_G/target.h
  src/main/target/IFF4_TWIN_G/target.mk
  src/main/target/IFF7_TWIN_G/target.h
  src/main/target/KAKUTEF7/target.h
  src/main/target/KAKUTEF7HDV/target.h
  src/main/target/TALONF7FUSION/config.c
  src/main/target/TALONF7FUSION/target.h
Labels: 030-maint

#244 MAMBA F722 Target: I2C share UART3, add drivers for Baro and Magnetometer
  src/main/target/MAMBAF722/target.h
  src/main/target/MAMBAF722/target.mk
Labels: 030-maint
