Repository emuflight/EmuFlight, pull requests merged in 2020-04, with the labels that each got.

#153 thrust linearization
  src/main/cms/cms_menu_imu.c
  src/main/fc/controlrate_profile.c
  src/main/fc/controlrate_profile.h
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/msp.c
  src/main/interface/settings.c
  src/main/sensors/battery.c
  src/main/sensors/battery.h
Labels: enhancement

#156 Update max7456_symbols.h
  src/main/drivers/max7456_symbols.h
Labels: bug

#122 Stick pids
  src/main/blackbox/blackbox.c
  src/main/build/version.h
  src/main/cms/cms_menu_imu.c
  src/main/common/kalman.c
  src/main/fc/controlrate_profile.c
  src/main/fc/controlrate_profile.h
  src/main/fc/fc_rc.c
  src/main/fc/fc_rc.h
  src/main/fc/rc_adjustments.c
  src/main/fc/rc_adjustments.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/msp.c
  src/main/interface/msp_protocol.h
  src/main/interface/settings.c
  src/main/target/ALIENWHOOP/config.c
  src/main/target/HELIOSPRING/target.h
  src/main/target/MODE2FLUX/target.h
  src/main/target/STRIXF10/target.h
  src/test/unit/pid_unittest.cc
Labels: feature, help wanted

#158 revert #153
  .travis.sh
  src/main/build/version.h
  src/main/cms/cms_menu_imu.c
  src/main/fc/controlrate_profile.c
  src/main/fc/controlrate_profile.h
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/msp.c
  src/main/interface/settings.c
  src/main/sensors/battery.c
  src/main/sensors/battery.h
Labels: bug

#185 github actions compile fix
  .github/workflows/build.yml
Labels: wontfix

#190 Fix bug with logging.
  src/main/flight/pid.c
Labels: bug
