Repository emuflight/EmuFlight, pull requests merged in 2020-12, with the labels that each got.

#419 add speedybeef7v2
  src/main/target/SPEEDYBEEF7V2/config.c
  src/main/target/SPEEDYBEEF7V2/target.c
  src/main/target/SPEEDYBEEF7V2/target.h
  src/main/target/SPEEDYBEEF7V2/target.mk
Labels: target/new

#427 add target TRANSTECF405HD
  src/main/target/TRANSTECF405HD/target.c
  src/main/target/TRANSTECF405HD/target.h
  src/main/target/TRANSTECF405HD/target.mk
Labels: target/new

#408 NBDHMBF4PRO (NewBeeDrone Hummingbird F4 Pro)
  make/source.mk
  src/main/cms/cms_menu_builtin.c
  src/main/cms/cms_menu_vtx_beesign.c
  src/main/cms/cms_menu_vtx_beesign.h
  src/main/drivers/beesign.c
  src/main/drivers/beesign.h
  src/main/drivers/max7456.c
  src/main/drivers/vtx_common.h
  src/main/fc/fc_init.c
  src/main/fc/fc_tasks.c
  src/main/interface/cli.c
  src/main/interface/msp.c
  src/main/interface/msp_box.c
  src/main/io/serial.h
  src/main/io/spektrum_vtx_control.c
  src/main/io/spektrum_vtx_control.h
  src/main/io/vtx_beesign.c
  src/main/io/vtx_beesign.h
  src/main/scheduler/scheduler.h
  src/main/sensors/gyro.c
  src/main/target/NBDHMBF4PRO/HMBF4PRO_INTL.mk
  src/main/target/NBDHMBF4PRO/HMBF4PRO_US.mk
  src/main/target/NBDHMBF4PRO/config.c
  src/main/target/NBDHMBF4PRO/target.c
  src/main/target/NBDHMBF4PRO/target.h
  src/main/target/NBDHMBF4PRO/target.mk
  src/main/telemetry/srxl.c
Labels: target/new

#409 NBDBBBLV2 (NewBeeDrone BeeBrain Lite v2)
  src/main/target/NBDBBBLV2/BEEBRAIN_BL_V2_WHOOP_INTL.mk
  src/main/target/NBDBBBLV2/BEEBRAIN_BL_V2_WHOOP_US.mk
  src/main/target/NBDBBBLV2/config.c
  src/main/target/NBDBBBLV2/target.c
  src/main/target/NBDBBBLV2/target.h
  src/main/target/NBDBBBLV2/target.mk
Labels: target/new

#431 FPORT fix: port of Betaflight https://github.com/betaflight/betaflight/pull/10388
  src/main/drivers/serial_uart_stm32f30x.c
  src/main/drivers/serial_uart_stm32f7xx.c
Labels: merge-able if approved

#426 add target PYRODRONEF4PDB
  src/main/target/PYRODRONEF4PDB/config.c
  src/main/target/PYRODRONEF4PDB/target.c
  src/main/target/PYRODRONEF4PDB/target.h
  src/main/target/PYRODRONEF4PDB/target.mk
Labels: target/new

#439 Nbd cricket f7 Target addition
  src/main/target/NBDCRICKETF7/config.c
  src/main/target/NBDCRICKETF7/target.c
  src/main/target/NBDCRICKETF7/target.h
  src/main/target/NBDCRICKETF7/target.mk
Labels: merge-able if approved, target/new

#446 Avarage cell voltage for CSRF
  src/main/telemetry/crsf.c
Labels: Fix

#436 NFE as a switch
  src/main/blackbox/blackbox.c
  src/main/cms/cms_menu_imu.c
  src/main/common/maths.h
  src/main/fc/config.c
  src/main/fc/fc_core.c
  src/main/fc/rc_modes.h
  src/main/fc/runtime_config.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/msp.c
  src/main/interface/msp_box.c
  src/main/interface/settings.c
  src/main/io/osd.c
Labels: merge-able if approved

#417 enhancement: CLI: allow vtx power to be changed by a switch
  src/main/interface/cli.c
  src/main/io/vtx_control.c
  src/main/io/vtx_control.h
  src/test/Makefile
  src/test/unit/cli_unittest.cc
  src/test/unit/vtx_unittest.cc
Labels: enhancement, merge-able if approved

#388 port of betaflight#10243 - add optional high framerate on screen display
  src/main/fc/fc_tasks.c
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/io/osd.h
Labels: enhancement, merge-able if approved

#400 port of betaflight#9878 - Added option to show cell value instead of batt value at stats screen
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/io/osd.h
Labels: enhancement

#401 port of betaflight#9637 - Add osd element showing percentage of mah used
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/io/osd.h
Labels: enhancement, requires-GUI-modification

#443 ImmersionRC GHST protocol
  make/source.mk
  src/main/drivers/serial.h
  src/main/interface/settings.c
  src/main/rx/ghst.c
  src/main/rx/ghst.h
  src/main/rx/ghst_protocol.h
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/target/common_fc_post.h
  src/main/target/common_fc_pre.h
  src/main/telemetry/ghst.c
  src/main/telemetry/ghst.h
  src/main/telemetry/telemetry.c
  src/main/telemetry/telemetry.h
  src/test/Makefile
  src/test/unit/rx_ghst_unittest.cc
  src/test/unit/telemetry_ghst_unittest.cc
Labels: feature, merge-able if approved, requires-GUI-modification
