Repository emuflight/EmuFlight, pull requests merged in 2021-06, with the labels that each got.

#502 fix yaw from causing motor increase. fix in 2pass mode skipping smooth mode for now.
  src/main/blackbox/blackbox.c
  src/main/cms/cms_menu_imu.c
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/settings.c
Labels: merge-able if approved

#579 Small filter efficiency improvements
  src/main/common/filter.c
  src/main/common/maths.h
Labels: in-testing, merge-able if approved

#566 Change VTX powers labels
  src/main/io/vtx_beesign.c
  src/main/io/vtx_smartaudio.c
  src/main/io/vtx_tramp.c
  src/test/unit/vtx_unittest.cc
Labels: in-testing, merge-able if approved

#583 Smith-Predictor on/off toggle [smith_predict_enabled]
  src/main/blackbox/blackbox.c
  src/main/cms/cms_menu_imu.c
  src/main/interface/settings.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
Labels: merge-able if approved

#571 Prevent a division of zero in the battery current measure
  src/main/sensors/current.c
Labels: in-testing, merge-able if approved

#570 Fix Barometer pressure calculation
  src/main/interface/settings.c
  src/main/sensors/barometer.c
Labels: in-testing, merge-able if approved

#562 add pt2-pt4 no longer suggest users use BIQUAD
  src/main/cms/cms_menu_imu.c
  src/main/common/filter.c
  src/main/common/filter.h
  src/main/flight/pid.c
  src/main/interface/settings.c
  src/main/sensors/gyro.c
  src/main/target/ALIENWHOOP/config.c
  src/main/target/BEEBRAIN_BL/config.c
Labels: in-testing

#541 update the kalman filter
  src/main/blackbox/blackbox.c
  src/main/cms/cms_menu_imu.c
  src/main/common/kalman.c
  src/main/common/kalman.h
  src/main/interface/msp.c
  src/main/interface/settings.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/gyro_filter_impl.h
Labels: in-testing, merge-able if approved
