Repository emuflight/EmuFlight, pull requests merged in 2021-08, with the labels that each got.

#657 fix PR#500; dynamicFilter/dynamicDtermNotch
  src/main/common/sdft.c
  src/main/flight/pid.c
  src/main/sensors/gyroanalyse.c
Labels: 0.4.0, merge-able if approved

#637 Fix Gyro KAKUTEF4V2
  src/main/target/KAKUTEF4/target.h
  src/main/target/KAKUTEF4/target.mk
Labels: merge-able if approved, target/bugfix

#500 update the Matrix filter, turn it into a dynamic notch filter
  make/source.mk
  src/main/blackbox/blackbox.c
  src/main/cms/cms_menu_imu.c
  src/main/common/filter.c
  src/main/common/maths.h
  src/main/common/sdft.c
  src/main/common/sdft.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/msp.c
  src/main/interface/settings.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/gyro_filter_impl.h
  src/main/sensors/gyroanalyse.c
  src/main/sensors/gyroanalyse.h
Labels: 0.4.0, in-testing

#660 2PASS motor output mixer as default
  src/main/flight/pid.c
Labels: 0.4.0, merge-able if approved

#666 fix BBH for dynamic gyro notch q
  src/main/blackbox/blackbox.c
Labels: 0.4.0, merge-able if approved

#643 Fix level mode/horizon issues
  src/main/flight/imu.c
  src/main/flight/pid.c
Labels: merge-able if approved, in-testing, 0.4.0

#669 add ZeezF7 v2
  src/main/target/ZEEZ_ZEEZF7V2/target.c
  src/main/target/ZEEZ_ZEEZF7V2/target.h
  src/main/target/ZEEZ_ZEEZF7V2/target.mk
Labels: target/new

#624 BlackBox version string
  src/main/blackbox/blackbox.c
Labels: on-hold, 0.4.0

#661 MSP 1.51 for 0.4.0
  src/main/interface/msp.c
  src/main/interface/msp_protocol.h
Labels: in-testing, 0.4.0, Work In Progress / In Flux

#674 bump version 0.4.0
  src/main/build/version.h
Labels: 0.4.0

#686 adding target IFRC_IFLIGHT_F745_AIO
  src/main/target/IFRC_IFLIGHT_F745_AIO/target.c
  src/main/target/IFRC_IFLIGHT_F745_AIO/target.h
  src/main/target/IFRC_IFLIGHT_F745_AIO/target.mk
Labels: target/new

#681 IFRC_IFLIGHT_SUCCEX_E_F7
  src/main/target/IFRC_IFLIGHT_SUCCEX_E_F7/config.c
  src/main/target/IFRC_IFLIGHT_SUCCEX_E_F7/target.c
  src/main/target/IFRC_IFLIGHT_SUCCEX_E_F7/target.h
  src/main/target/IFRC_IFLIGHT_SUCCEX_E_F7/target.mk
Labels: target/new

#683 IFRC_IFLIGHT_SUCCEX_E_F4
  src/main/target/IFRC_IFLIGHT_SUCCEX_E_F4/target.c
  src/main/target/IFRC_IFLIGHT_SUCCEX_E_F4/target.h
  src/main/target/IFRC_IFLIGHT_SUCCEX_E_F4/target.mk
Labels: target/new

#687 IFRC_JBF7
  src/main/target/IFRC_JBF7/config.c
  src/main/target/IFRC_JBF7/target.c
  src/main/target/IFRC_JBF7/target.h
  src/main/target/IFRC_JBF7/target.mk
Labels: target/bugfix
