Repository emuflight/EmuFlight, pull requests merged in 2021-04, with the labels that each got.

#542 Gyro ABG filter apply
  src/main/sensors/gyro_filter_impl.h
Labels: merge-able if approved

#545 fix half life
  src/main/common/filter.c
Labels: merge-able if approved

#546 kakute f7 mini v3
  src/main/target/KAKUTEF7MINIV3/target.c
  src/main/target/KAKUTEF7MINIV3/target.h
  src/main/target/KAKUTEF7MINIV3/target.mk
Labels: merge-able if approved, target/new

#549 BBL headers for ABG
  src/main/blackbox/blackbox.c
Labels: merge-able if approved

#544 bump version 0.3.5
  src/main/build/version.h
Labels: merge-able if approved

#514 Fix CPU status, UART Listing, and Add calibrate accelerometer CLI command
  src/main/cli/cli.c
Labels: 1.0.0
