Repository emuflight/EmuFlight, pull requests merged in 2021-03, with the labels that each got.

#489 CLI Status commands for Nemesis and EmuFlight 1.0.0
  src/main/cli/cli.c
Labels: 1.0.0

#516 specify "uncommitted" in .hex & .bin when applicable
  Makefile
Labels: merge-able if approved

#506 Improved CRSF flight mode reporting.
  src/main/telemetry/crsf.c
Labels: enhancement
