Repository emuflight/EmuFlight, pull requests merged in 2021-05, with the labels that each got.

#537 add kiss and actual rates
  src/main/fc/controlrate_profile.h
  src/main/fc/fc_rc.c
  src/main/interface/settings.c
Labels: feature, merge-able if approved, requires-GUI-modification

#554 Update blackbox.c
  src/main/blackbox/blackbox.c
Labels: bug, enhancement, merge-able if approved

#560 slightly better github actions
  .github/workflows/build.yml
Labels: merge-able if approved

#531 increase auto detect cell count to 12
  src/main/sensors/battery.h
Labels: enhancement

#572 Remove unused CLI variables from documentation
  docs/Cli.md
  docs/Gtune.md
  docs/Migrating from baseflight.md
  docs/Mixer.md
  docs/PID tuning.md
  docs/Profiles.md
  docs/Release Notes/Betaflight 3.4 Release Notes.md
  docs/Rx.md
  docs/Telemetry.md
  docs/Upgrading/Upgrading from 3.2 to 3.3.md
  src/main/target/ALIENWHOOP/config.c
Labels: merge-able if approved
