Repository emuflight/EmuFlight, pull requests merged in 2022-06, with the labels that each got.

#515 Add GPS telemetry support to GHST protocol
  src/main/rx/ghst_protocol.h
  src/main/telemetry/ghst.c
Labels: enhancement, 0.4.1

#808 Improve peak estimation
  src/main/sensors/gyroanalyse.c
Labels: merge-able if approved, in-testing, 0.4.1

#814 yaw_spin_recovery AUTO
  src/main/fc/fc_rc.c
  src/main/interface/settings.c
  src/main/interface/settings.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
Labels: help wanted, 0.4.1

#815 port "widening range of BLHeli/_S device id BF#11513"
  src/main/io/serial_4way.c
Labels: help wanted, 0.4.1
