Repository emuflight/EmuFlight, pull requests merged in 2022-07, with the labels that each got.

#818 default 1.5khz logging
  src/main/blackbox/blackbox.c
Labels: merge-able if approved, 0.4.1

#820 revert rc-smoothing to interpolation (manual 21 RPTY)
  src/main/pg/rx.c
Labels: help wanted, merge-able if approved, 0.4.1

#831 Revert "default vtx_low_power_disarm = ON"
  src/main/drivers/vtx_common.h
Labels: 0.4.1

#585 FF_RACEPIT Beeper resource use C03
  src/main/target/FF_RACEPIT/target.h
Labels: help wanted

#834 bump version 0.4.1
  src/main/build/version.h
Labels: 0.4.1

#835 TARGET ZEUS722_AIO
  src/main/target/ZEUSF722_AIO/config.c
  src/main/target/ZEUSF722_AIO/target.c
  src/main/target/ZEUSF722_AIO/target.h
  src/main/target/ZEUSF722_AIO/target.mk
Labels: merge-able if approved, 0.4.1

#836 TARGET GEPRCF405
  src/main/target/GEPRCF405/config.c
  src/main/target/GEPRCF405/target.c
  src/main/target/GEPRCF405/target.h
  src/main/target/GEPRCF405/target.mk
Labels: merge-able if approved, 0.4.1

#837 TARGET RUSH_BLADE_F7_HD
  src/main/target/RUSH_BLADE_F7_HD/target.c
  src/main/target/RUSH_BLADE_F7_HD/target.h
  src/main/target/RUSH_BLADE_F7_HD/target.mk
Labels: merge-able if approved, 0.4.1

#838 Target LDARC_F411
  src/main/target/LDARC_F411/target.c
  src/main/target/LDARC_F411/target.h
  src/main/target/LDARC_F411/target.mk
Labels: merge-able if approved, 0.4.1

#841 Target ZEUSF4F4
  src/main/target/ZEUSF4FR/target.c
  src/main/target/ZEUSF4FR/target.h
  src/main/target/ZEUSF4FR/target.mk
Labels: merge-able if approved, 0.4.1

#842 Target FOXEERF745
  src/main/target/FOXEERF745_AIO/target.c
  src/main/target/FOXEERF745_AIO/target.h
  src/main/target/FOXEERF745_AIO/target.mk
Labels: merge-able if approved, 0.4.1

#843 TARGET IFLIGHT_BLITZ_F405
  src/main/target/IFLIGHT_BLITZ_F405/target.c
  src/main/target/IFLIGHT_BLITZ_F405/target.h
  src/main/target/IFLIGHT_BLITZ_F405/target.mk
Labels: merge-able if approved, 0.4.1

#844 TARGET GEPRCF411_PRO
  src/main/target/GEPRCF411_AIO/target.c
  src/main/target/GEPRCF411_AIO/target.h
  src/main/target/GEPRCF411_AIO/target.mk
Labels: merge-able if approved, 0.4.1

#845 TARGET ZEUSF4EVO
  src/main/target/ZEUSF4EVO/target.c
  src/main/target/ZEUSF4EVO/target.h
  src/main/target/ZEUSF4EVO/target.mk
Labels: merge-able if approved, 0.4.1

#846 TARGET JHEMCUF405
  src/main/target/JHEMCUF405/target.c
  src/main/target/JHEMCUF405/target.h
  src/main/target/JHEMCUF405/target.mk
Labels: merge-able if approved, 0.4.1

#847 TARGET HAKRCF722D
  src/main/target/HAKRCF722D/config.c
  src/main/target/HAKRCF722D/target.c
  src/main/target/HAKRCF722D/target.h
  src/main/target/HAKRCF722D/target.mk
Labels: merge-able if approved, 0.4.1

#773 Target JHEF_JHEF405PRO
  src/main/target/JHEF405PRO/config.c
  src/main/target/JHEF405PRO/target.c
  src/main/target/JHEF405PRO/target.h
  src/main/target/JHEF405PRO/target.mk
Labels: target/new, merge-able if approved, in-testing-needs-testing
